### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by stevelyall** [mitchhentges/john-cena-theme-linux-beep#1]
Expected behaviour: Should beep an awesome song

Actual bevahiour: Doesn't beep

**Comment by mitchhentges** [comment]
Do you have `beep` installed?
Laptops generally don't have those old speaker-things anyways, so that might explain it

**Comment by LeeBergstrand** [comment]
OSX has no hardware speaker support.

Could try this:

``` shell
say -v Bells "beep bap boop beep bap boop"
```

But you might need to work on your quire skills.

``` shell
say "Your time is up, my time is now. You can't see me, my time is now. It's the franchise, boy I'm shinin' now. You can't see me, my time is now!"
```

ps:

``` shell
say "Sorry steve I can't do that..."
```

**Comment by stevelyall** [comment]
Well then Apple should update OSX to give it hardware speaker support! :P

**Comment by mitchhentges** [comment]
Tough. gg apple
